In [1]:
import torch

In [6]:
y_hat = torch.rand((2,4))
y = torch.rand((2,4))

In [161]:
def si_snr_2speaker(y_hat, y):
    
    y_power = torch.pow(y, 2).sum(-1, keepdim=False)
    
    scale_factor = y_hat@y.t()/y_power

    s_target = (torch.pow(y.unsqueeze(1) * scale_factor.t().unsqueeze(-1), 2).sum(-1)).t()

    #e_noise
    residual = y_hat.unsqueeze(1) - y
    residual_norms = torch.pow(residual, 2).sum(-1, keepdim=False)
    
    temp = (10*(torch.log10(s_target) - torch.log10(residual_norms)))
    
    loss_one = temp[0,0] + temp[1,1]
    loss_two = temp[0,1] + temp[1,0]
    maximum_loss = loss_one if loss_one > loss_two else loss_two
    
    return maximum_loss
    

In [162]:
res = si_snr(y_hat, y)

scale_factor tensor([[1.0502, 1.5522],
        [0.3763, 0.6053]])
starget tensor([[0.9849, 0.7627],
        [0.1264, 0.1160]])
tensor([[0.3853, 0.7018],
        [0.5830, 0.2953]])


In [163]:
res

tensor(0.0169)

In [ ]:
#residuals

In [115]:
torch.pow(y_hat[0] - y[0], 2).sum(), torch.pow(y_hat[0] - y[1], 2).sum()

(tensor(0.3853), tensor(0.7018))

In [116]:
torch.pow(y_hat[1] - y[0], 2).sum(), torch.pow(y_hat[1] - y[1], 2).sum()

(tensor(0.5830), tensor(0.2953))

In [147]:
res.unsqueeze(0), res.unsqueeze(1).shape

(tensor([[[ 4.0760,  0.3616],
          [-6.6386, -4.0591]]]),
 torch.Size([2, 1, 2]))

In [151]:
res.t()

tensor([[ 4.0760, -6.6386],
        [ 0.3616, -4.0591]])

In [109]:
((y[1] * 1.5522)**2).sum(), ((y[1]*0.6053)**2).sum()

(tensor(0.7627), tensor(0.1160))

In [108]:
((y[0] * 1.0502)**2).sum(), ((y[0]*0.3763)**2).sum()

(tensor(0.9848), tensor(0.1264))

In [87]:
y.unsqueeze(1).shape 

torch.Size([2, 1, 4])

In [35]:
norms =torch.pow(y, 2).sum(-1)
norms

tensor([0.8929, 0.3166])

In [36]:
#primeira parte

In [63]:
t_0 = (y[0] * y_hat[1]).sum()
t_1 = (y[1] * y_hat[1]).sum()
t_0, t_1

(tensor(0.3360), tensor(0.1916))

In [66]:
#residuals

In [71]:
dif_0 = torch.pow(y_hat[0] - y[0],2).sum()
dif_1 = torch.pow(y_hat[1] - y[0], 2).sum()
dif_0, dif_1

(tensor(0.3853), tensor(0.5830))

In [45]:
t_0 = t_0/norms[0]
t_1 = t_1/norms[1]
t_0, t_1

(tensor(0.3763), tensor(1.5522))

In [39]:
s_0 = t_0 * y[0]
s_1 = t_1 * y[1]
s_0 = torch.pow(s_0, 2).sum()
s_1 = torch.pow(s_1, 2).sum()
s_0, s_1

(tensor(0.9849), tensor(0.1160))

In [41]:
10*(torch.log10(s_0) - torch.log10(dif_0)) + 10*(torch.log10(s_1) - torch.log10(dif_1))

tensor(0.0169)